source "https://rubygems.org"

gem 'capybara'
gem "cucumber", "3.2.0"
gem 'report_builder'
gem 'rspec'
gem 'selenium-webdriver'
gem "faker", git: "https://github.com/faker-ruby/faker.git", branch: "master"
gem "brazilian_documents", "~> 0.1.4"
gem "ffi"
gem "rufo"
