source "https://rubygems.org"

gem 'capybara'
gem "cucumber", "3.2.0"
gem 'report_builder'
gem 'rspec', '3.8.0'
gem 'selenium-webdriver'
gem "faker", git: "https://github.com/faker-ruby/faker.git", branch: "master"