source "https://rubygems.org"

gem 'capybara', "3.28.0"
gem "cucumber", "3.2.0"
gem 'report_builder', "1.8"
gem 'rspec'
gem 'selenium-webdriver'
gem "brazilian_documents", "~> 0.1.4"
gem "faker", git: "https://github.com/faker-ruby/faker.git", branch: "master"
gem 'rufo'
gem 'ffi'
gem 'yaml'
gem 'pry'
gem "cpf_faker"